# docker-compose.yml
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vilt_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8010:8000"
    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8
    container_name: vilt_mysql
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vilt_app
      MYSQL_USER: vilt_user
      MYSQL_PASSWORD: vilt_pass
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    image: node:18
    container_name: vilt_node
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5174:5173"

volumes:
  mysql_data:
